main = '''#                 [ AccuRT main configuration file ]                 

SOURCE_TYPE = 
$SOURCE_TYPE

SOURCE_SCALING_FACTOR = $SOURCE_SCALING_FACTOR

SOURCE_ZENITH_ANGLE = $SOURCE_ZENITH_ANGLE

BOTTOM_BOUNDARY_SURFACE = $BOTTOM_BOUNDARY_SURFACE

BOTTOM_BOUNDARY_SURFACE_SCALING_FACTOR = $BOTTOM_BOUNDARY_SURFACE_SCALING_FACTOR

STREAM_UPPER_SLAB_SIZE = $STREAM_UPPER_SLAB_SIZE

STREAM_LOWER_SLAB_PARAMETERS = $STREAM_LOWER_SLAB_PARAMETERS

LAYER_DEPTHS_UPPER_SLAB = 
$LAYER_DEPTHS_UPPER_SLAB

LAYER_DEPTHS_LOWER_SLAB = 
$LAYER_DEPTHS_LOWER_SLAB

MATERIALS_INCLUDED_UPPER_SLAB = $MATERIALS_INCLUDED_UPPER_SLAB

MATERIALS_INCLUDED_LOWER_SLAB = $MATERIALS_INCLUDED_LOWER_SLAB

DETECTOR_DEPTHS_UPPER_SLAB = $DETECTOR_DEPTHS_UPPER_SLAB

DETECTOR_DEPTHS_LOWER_SLAB = $DETECTOR_DEPTHS_LOWER_SLAB

DETECTOR_AZIMUTH_ANGLES = $DETECTOR_AZIMUTH_ANGLES

DETECTOR_POLAR_ANGLES = $DETECTOR_POLAR_ANGLES

DETECTOR_WAVELENGTHS = $DETECTOR_WAVELENGTHS

DETECTOR_WAVELENGTH_BAND_WIDTHS = 
$DETECTOR_WAVELENGTH_BAND_WIDTHS

SAVE_SINE_IRRADIANCE = SAVE_SINE_IRRADIANCE

SAVE_SCALAR_IRRADIANCE = $SAVE_SCALAR_IRRADIANCE

SAVE_RADIANCE = $SAVE_RADIANCE

SAVE_IOPS = $SAVE_IOPS

SAVE_BOTTOM_BOUNDARY_SURFACE = $SAVE_BOTTOM_BOUNDARY_SURFACE

SAVE_MATERIAL_PROFILE = $SAVE_MATERIAL_PROFILE

PROFILE_OUTPUT_WAVELENGTH = $PROFILE_OUTPUT_WAVELENGTH

PRINT_PROGRESS_TO_SCREEN = $PRINT_PROGRESS_TO_SCREEN

REPEATED_RUN_SIZE = $REPEATED_RUN_SIZE

#                   End of main configuration tags
'''



ice  = '''## AccuRT configuration file for ice material ##


PROFILE_LABEL = $PROFILE_LABEL

BRINE_PROFILE  = 
$BRINE_PROFILE

BUBBLE_PROFILE =
$BUBBLE_PROFILE

BRINE_EFFECTIVE_RADIUS =
$BRINE_EFFECTIVE_RADIUS

BUBBLE_EFFECTIVE_RADIUS = 
$BUBBLE_EFFECTIVE_RADIUS

IMPURITY_PROFILE =
$IMPURITY_PROFILE

IMPURITY_IMAG = $IMPURITY_IMAG

INTERNAL_MIXING = $INTERNAL_MIXING

USE_HG_PHASE_FUNCTION_OVERRIDE = $USE_HG_PHASE_FUNCTION_OVERRIDE

USE_PARAMETERIZED_MIE_CODE = $USE_PARAMETERIZED_MIE_CODE

BRINE_SIZE_DISTRIBUTION_WIDTH = 
$BRINE_SIZE_DISTRIBUTION_WIDTH

BUBBLE_SIZE_DISTRIBUTION_WIDTH = 
$BUBBLE_SIZE_DISTRIBUTION_WIDTH

QUADRATURE_POINTS = $QUADRATURE_POINTS

# End of ice configuration file
'''



templates = {'ice': ice, 'main': main}


def gettemplates():
	return templates
